# Welcome to Jekyll!
#

# Site settings
title: nikhil kuriakose
description: |
  Frontend/Backend Developer, India
owner: nikhil kuriakose # or company name
first_published: 2016 # if migrating another site, the year of your first publish
fist_job: Aug 2010
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
wordpress: https://supercompiler.wordpress.com
social:
  #email: nikhilkuria@gmail.com
  twitter: https://twitter.com/nikhilkuria
  github: https://github.com/nikhilkuria
  linkedin-square: https://in.linkedin.com/in/nikhil-kuriakose-0a98a02b
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
